-- Generated by script2lua.
-- Source: npc/test/infinite_warp.txt
return {
	warps = {
		{
			line = 12,
			w1 = "e_tower,74,116,0",
			w2 = "warp",
			w3 = "#inf_warp1_1",
			w4 = "2,2,e_tower,81,108",
		},
		{
			line = 13,
			w1 = "e_tower,81,108,0",
			w2 = "warp",
			w3 = "#inf_warp1_2",
			w4 = "2,2,e_tower,75,84",
		},
		{
			line = 14,
			w1 = "e_tower,75,84,0",
			w2 = "warp",
			w3 = "#inf_warp1_3",
			w4 = "2,2,e_tower,74,116",
		},
		{
			line = 17,
			w1 = "e_tower,76,95,0",
			w2 = "warp",
			w3 = "#inf_warp2_1",
			w4 = "2,2,alb2trea,84,48",
		},
		{
			line = 18,
			w1 = "alb2trea,84,48,0",
			w2 = "warp",
			w3 = "#inf_warp2_2",
			w4 = "2,2,guild_vs5,58,50",
		},
		{
			line = 19,
			w1 = "guild_vs5,58,50,0",
			w2 = "warp",
			w3 = "#inf_warp2_3",
			w4 = "2,2,e_tower,76,95",
		},
		{
			line = 22,
			w1 = "ecl_tdun04,26,31,0",
			w2 = "warp",
			w3 = "#inf_warp3_1",
			w4 = "20,20,prontera,100,100",
		},
	},
	monsters = {
	},
	mapflags = {
	},
	shops = {
	},
	duplicates = {
	},
	scripts = {
	},
	functions = {
	},
}
