-- Generated by script2lua.
-- Source: npc/test/npc_test_longvar.txt
return {
	warps = {
	},
	monsters = {
	},
	mapflags = {
	},
	shops = {
	},
	duplicates = {
	},
	scripts = {
		{
			line = 12,
			w1 = "prontera,155,176,3",
			w2 = "script",
			w3 = "Pront Test",
			w4 = "77,",
			main = function(ctx)
				local _ENV = ctx:env()
				mes("Testing to store long variable on char-serv")
				-- test1 long value
				test$ = "0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345"
				-- test2 normal length
				test2$ = "anything really, doesn't matter at this point"
				-- test3 long key (41)
				thisisareallylongkeyImeanReallyReallyLong$ = "gotcha"
				-- test4 long key 2 (with int)
				ReallyReallyReallyReallyReallyReallyLong = 42
				return
			end,
			events = {
			},
			labels = {
			},
		},
	},
	functions = {
	},
}
