-- Generated by script2lua.
-- Source: npc/test/npc_test_checkweight.txt
return {
	warps = {
	},
	monsters = {
	},
	mapflags = {
	},
	shops = {
	},
	duplicates = {
	},
	scripts = {
		{
			line = 11,
			w1 = "prontera,161,181,6",
			w2 = "script",
			w3 = "ChkSpace",
			w4 = "763,",
			main = function(ctx)
				local _ENV = ctx:env()
				_ENV["function"](ChkResult)
				_ENV["function"](FinalReport)
			end,
			events = {
			},
			labels = {
				["L_RESET"] = function(ctx)
					local _ENV = ctx:env()
					resetlvl(1)
					getinventorylist()
					delitem(_ENV["@inventorylist_id"][_ENV[".@i"]], _ENV["@inventorylist_amount"][_ENV[".@i"]])
					-- clear inventory
					L_TEST1: _ENV[".@testid"] = 0
					_ENV[".@success"] = 0
					_ENV[".@ret"] = checkweight(512,10)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,1,_ENV[".@ret"]))
					-- should be success
					_ENV[".@ret"] = checkweight("Apple",10)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,1,_ENV[".@ret"]))
					-- should be success
					_ENV[".@ret"] = checkweight(6320,33000)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure too many item amount item weight=0
					_ENV[".@ret"] = checkweight("Premium_Reset_Stone",33000)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure too many item amount
					_ENV[".@ret"] = checkweight(717,500)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,1,_ENV[".@ret"]))
					-- should be success weight based on max weight=2030
					_ENV[".@ret"] = checkweight(717,1000)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure weight based on max weight=2030
					_ENV[".@ret"] = checkweight(2794,100)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,1,_ENV[".@ret"]))
					-- should be success
					_ENV[".@ret"] = checkweight(2794,101)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure (with MAX_INVENTORY = 100)
					_ENV[".@ret"] = checkweight(-1,1)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure invalid item id
					_ENV[".@ret"] = checkweight(512,0)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure invalid amount
					debugmes("End backward test")
					FinalReport(_ENV[".@testid"], _ENV[".@success"])
					L_TEST2: _ENV[".@testid"] = 0
					_ENV[".@success"] = 0
					_ENV[".@ret"] = checkweight(512,10,513,10)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,1,_ENV[".@ret"]))
					-- should be success
					_ENV[".@ret"] = checkweight("Apple",10,"Banana",10)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,1,_ENV[".@ret"]))
					-- should be success
					_ENV[".@ret"] = checkweight(512,80,513,33000)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure
					_ENV[".@ret"] = checkweight("Apple",80,"Banana",33000)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure too many item amount
					_ENV[".@ret"] = checkweight("Apple",10,"Banana",21,512)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure invalid nb of args
					_ENV[".@ret"] = checkweight(717,500,716,100)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,1,_ENV[".@ret"]))
					-- should be succes weight 1800/2030
					_ENV[".@ret"] = checkweight(717,500,716,500)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure weight 3000/2030
					_ENV[".@ret"] = checkweight(2794,95,2795,5)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,1,_ENV[".@ret"]))
					-- should be success
					_ENV[".@ret"] = checkweight(2794,95,2795,10)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure (with MAX_INVENTORY = 100)
					_ENV[".@ret"] = checkweight(512,1,-1,1)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure invalid item id
					_ENV[".@ret"] = checkweight(512,1,513,0)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure invalid amount
					_ENV[".@ret"] = checkweight(6320,31000,6320,2000)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure overamount inventory
					_ENV[".@ret"] = checkweight(512,1,513,1,514,1,515,1)
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,1,_ENV[".@ret"]))
					-- should be success
					debugmes("End update by list tests")
					FinalReport(_ENV[".@testid"], _ENV[".@success"])
					L_TEST3: _ENV[".@testid"] = 0
					_ENV[".@success"] = 0
					setarray(_ENV[".@item"][0], 512, 513, 514, 515)
					setarray(_ENV[".@count"][0], 1, 5, 9, 12)
					_ENV[".@ret"] = checkweight2(_ENV[".@item"],_ENV[".@count"])
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,1,_ENV[".@ret"]))
					-- should be success
					cleararray(_ENV[".@item"][0], 0, 4)
					cleararray(_ENV[".@count"][0], 0, 4)
					setarray(_ENV[".@item"][0], 512, 513, 514, 515)
					setarray(_ENV[".@count"][0], 1, 5, -1, 12)
					_ENV[".@ret"] = checkweight2(_ENV[".@item"],_ENV[".@count"])
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure, invalid amount
					cleararray(_ENV[".@item"][0], 0, 4)
					cleararray(_ENV[".@count"][0], 0, 4)
					setarray(_ENV[".@item"][0], 512, 513, 514, -1)
					setarray(_ENV[".@count"][0], 1, 5, 15, 12)
					_ENV[".@ret"] = checkweight2(_ENV[".@item"],_ENV[".@count"])
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure, invalid id
					cleararray(_ENV[".@item"][0], 0, 4)
					cleararray(_ENV[".@count"][0], 0, 4)
					setarray(_ENV[".@item"][0], 717, 715, 716, 714)
					setarray(_ENV[".@count"][0], 300, 300, 300, 300)
					_ENV[".@ret"] = checkweight2(_ENV[".@item"],_ENV[".@count"])
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure, total by weight
					cleararray(_ENV[".@item"][0], 0, 4)
					cleararray(_ENV[".@count"][0], 0, 4)
					setarray(_ENV[".@item"][0], 6320, 6320)
					setarray(_ENV[".@count"][0], 31000, 2000)
					_ENV[".@ret"] = checkweight2(_ENV[".@item"],_ENV[".@count"])
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure, total by weight
					cleararray(_ENV[".@item"][0], 0, 2)
					cleararray(_ENV[".@count"][0], 0, 2)
					setarray(_ENV[".@item"][0], 2794, 2795)
					setarray(_ENV[".@count"][0], 95, 5)
					_ENV[".@ret"] = checkweight2(_ENV[".@item"],_ENV[".@count"])
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,1,_ENV[".@ret"]))
					-- should be success
					setarray(_ENV[".@count"][0], 95, 10)
					_ENV[".@ret"] = checkweight2(_ENV[".@item"],_ENV[".@count"])
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure overamount item
					cleararray(_ENV[".@item"][0], 0, 2)
					cleararray(_ENV[".@count"][0], 0, 2)
					setarray(_ENV[".@item"][0], 6320, 6320, 512)
					setarray(_ENV[".@count"][0], 1, 3)
					_ENV[".@ret"] = checkweight2(_ENV[".@item"],_ENV[".@count"])
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure, size mismatch
					cleararray(_ENV[".@item"][0], 0, 3)
					cleararray(_ENV[".@count"][0], 0, 2)
					setarray(_ENV[".@item"][0], 6320, 6321)
					setarray(_ENV[".@count"][0], 1, 3, 5)
					_ENV[".@ret"] = checkweight2(_ENV[".@item"],_ENV[".@count"])
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,0,_ENV[".@ret"]))
					-- should be failure, size mismatch
					set(".@weight_limit", MaxWeight)
					set("MaxWeight", 2147483647)
					-- currently maxweight is stored as uint32 (2^32-1)
					cleararray(_ENV[".@item"][0], 0, 2)
					cleararray(_ENV[".@count"][0], 0, 3)
					setarray(_ENV[".@item"][0], 714)
					setarray(_ENV[".@count"][0], 300)
					_ENV[".@ret"] = checkweight2(_ENV[".@item"],_ENV[".@count"])
					set("MaxWeight", _ENV[".@weight_limit"])
					set(".@success", _ENV[".@success"]+ChkResult(_ENV[".@testid"]++,1,_ENV[".@ret"]))
					-- should be success, (test weight over 65k)
					debugmes("End update by array tests")
					FinalReport(_ENV[".@testid"], _ENV[".@success"])
				end,
				["L_FINAL"] = function(ctx)
					local _ENV = ctx:env()
					return
					_ENV["function"](ChkResult { _ENV[".@tid"] = getarg(0))
					_ENV[".@expected"] = getarg(1)
					_ENV[".@ret"] = getarg(2)
					_ENV[".@success"] = (_ENV[".@ret"]==_ENV[".@expected"])
					debugmes((("Test "+_ENV[".@tid"]+" = "+(_ENV[".@success"]) and ("Success") or ("Fail"))))
					return(_ENV[".@success"])
					_ENV["function"](FinalReport { _ENV[".@tdone"] = getarg(0))
					_ENV[".@success"] = getarg(1)
					debugmes("Results = Pass : "+_ENV[".@success"]+"/"+_ENV[".@tdone"]+" Fails : "+(_ENV[".@tdone"]-_ENV[".@success"])+"/"+_ENV[".@tdone"])
					if _ENV[".@success"] ~= _ENV[".@tdone"] then
					debugmes("One or more failures have occurred. Enable chkresult print to find failed tests.")
					end
					return
				end,
			},
		},
	},
	functions = {
	},
}
