-- Generated by script2lua.
-- Source: npc/test/OnInterInit.txt
return {
	warps = {
	},
	monsters = {
	},
	mapflags = {
	},
	shops = {
	},
	duplicates = {
	},
	scripts = {
		{
			line = 11,
			w1 = "-",
			w2 = "script",
			w3 = "OnInterChk",
			w4 = "-1,",
			main = function(ctx)
				local _ENV = ctx:env()
				return
			end,
			events = {
				["OnInterIfInit"] = function(ctx)
					local _ENV = ctx:env()
					debugmes("Loaded OnInterIfInit <-------")
					return
				end,
				["OnInterIfInitOnce"] = function(ctx)
					local _ENV = ctx:env()
					debugmes("Loaded OnInterIfInitOnce <-------")
					return
				end,
			},
			labels = {
			},
		},
	},
	functions = {
	},
}
