-- Generated by script2lua.
-- Source: npc/test/ci/0000_funcs.txt
return {
	warps = {
	},
	monsters = {
	},
	mapflags = {
	},
	shops = {
	},
	duplicates = {
	},
	scripts = {
	},
	functions = {
		{
			line = 1,
			w1 = "function",
			w2 = "script",
			w3 = "AssertTrue",
			run = function(ctx, ...)
				local _ENV = ctx:env()
				if not getarg(0) then
				errormes("AssertTrue failed for " + getarg(1) + ".")
				return(false)
				end
				return(true)
			end,
			labels = {
			},
		},
		{
			line = 9,
			w1 = "function",
			w2 = "script",
			w3 = "AssertEquals",
			run = function(ctx, ...)
				local _ENV = ctx:env()
				if getarg(0) ~= getarg(1) then
				errormes("AssertEquals failed for " + getarg(2) + ": expected " + getarg(0) + ", got " + getarg(1) + ".")
				return(false)
				end
				return(true)
			end,
			labels = {
			},
		},
	},
}
