-- Generated by script2lua.
-- Source: npc/test/ci/5573.txt
return {
	warps = {
	},
	monsters = {
	},
	mapflags = {
	},
	shops = {
	},
	duplicates = {
	},
	scripts = {
		{
			line = 1,
			w1 = "-",
			w2 = "script",
			w3 = "Issue5573",
			w4 = "-1,",
			main = function(ctx)
				local _ENV = ctx:env()
				return
			end,
			events = {
				["OnInit"] = function(ctx)
					local _ENV = ctx:env()
					_ENV[".i"] = 0
					_ENV[".@i"] = min( _ENV[".i"], 200 )
					if _ENV[".@i"] == 200 then
					errormes("Issue 5573 is happening again.")
					end
				end,
			},
			labels = {
			},
		},
	},
	functions = {
	},
}
