-- Generated by script2lua.
-- Source: npc/test/ci/7291.txt
return {
	warps = {
	},
	monsters = {
	},
	mapflags = {
	},
	shops = {
	},
	duplicates = {
	},
	scripts = {
		{
			line = 1,
			w1 = "-",
			w2 = "script",
			w3 = "itemlink#ci",
			w4 = "-1,",
			main = function(ctx)
				local _ENV = ctx:env()
				return
			end,
			events = {
				["OnInit"] = function(ctx)
					local _ENV = ctx:env()
					if checkre(0) then
					if PACKETVER >= 20200724 then
					-- Change of separators and add grade
					_ENV[".@expected$"] = "<ITEML>0000213v0%0g&00'00)18X)1ck)00)00+2R,00-00</ITEML>"
					elseif PACKETVER >= 20161116 then
					-- Change of separators and add equip preview
					_ENV[".@expected$"] = "<ITEML>0000213v0%0g&00(18X(1ck(00(00*2R+00,00</ITEML>"
					elseif PACKETVER >= 20160113 then
					-- Change from <ITEM> to <ITEML>
					_ENV[".@expected$"] = "<ITEML>0000213v0%0g'18X'1ck'00'00)2R*00+00</ITEML>"
					elseif PACKETVER >= 20151104 then
					-- Initial version
					_ENV[".@expected$"] = "<ITEM>0000213v0%0g'18X'1ck'00'00)2R*00+00</ITEM>"
					end
					else({)
					-- Item Link does not exist (clientside) yet
					_ENV[".@expected$"] = "Crimson Saber"
					end
					setarray(".@opt_ids", RDMOPT_WEAPON_ATTR_GROUND)
					_ENV[".@actual$"] = itemlink(13454,16,4399,4608,0,0,0,_ENV[".@opt_ids"],_ENV[".@opt_dummy"],_ENV[".@opt_dummy"])
					AssertEquals(_ENV[".@expected$"], _ENV[".@actual$"], "Generated itemlink for +16 Earth Crimson Saber")
					else({)
					if PACKETVER >= 20200724 then
					-- Change of separators and add grade (not used in pre-renewal)
					_ENV[".@expected$"] = "<ITEML>000021hS%0a&00'00)18X)00)00)00</ITEML>"
					elseif PACKETVER >= 20161116 then
					-- Change of separators and add equip preview
					_ENV[".@expected$"] = "<ITEML>000021hS%0a&00(18X(00(00(00</ITEML>"
					elseif PACKETVER >= 20160113 then
					-- Change from <ITEM> to <ITEML>
					_ENV[".@expected$"] = "<ITEML>000021hS%0a'18X'00'00'00</ITEML>"
					elseif PACKETVER >= 20151104 then
					-- Initial version
					_ENV[".@expected$"] = "<ITEM>000021hS%0a'18X'00'00'00</ITEM>"
					end
					else({)
					-- Item Link does not exist (clientside) yet
					_ENV[".@expected$"] = "Blade"
					-- No Random Options in Pre-Renewal
					_ENV[".@actual$"] = itemlink(1108,10,4399)
					AssertEquals(_ENV[".@expected$"], _ENV[".@actual$"], "Generated itemlink for +10 Blade[4]")
				end,
			},
			labels = {
			},
		},
	},
	functions = {
	},
}
