-- Generated by script2lua.
-- Source: npc/test/ci/8886.txt
return {
	warps = {
	},
	monsters = {
	},
	mapflags = {
	},
	shops = {
	},
	duplicates = {
	},
	scripts = {
		{
			line = 1,
			w1 = "-",
			w2 = "script",
			w3 = "8886#ci",
			w4 = "-1,",
			main = function(ctx)
				local _ENV = ctx:env()
				return
			end,
			events = {
				["OnInit"] = function(ctx)
					local _ENV = ctx:env()
					atcommand("@broadcast Test")
					return
				end,
			},
			labels = {
			},
		},
	},
	functions = {
	},
}
